import json
from typing import TypedDict, List
from langgraph.graph import StateGraph, START, END

from app.tools.code.python_repl_tool import code_tool
from app.tools.file.file_manager_tool import get_file_tools
from app.tools.memory.chroma_tool import store_memory_tool, retrieve_memory_tool
from app.graph.state import AgentState

# Get file output tool specifically for executor
file_tools = get_file_tools()
output_tool = next(tool for tool in file_tools["output"] if "write_file" in tool.name)

def retrieve_node(state: AgentState) -> AgentState:
    """Retrieve relevant memories based on the query."""
    query = state.get("query", "No query provided")
    
    try:
        memories = retrieve_memory_tool.invoke({"query": query})
        status = "Retrieved memory successfully."
    except Exception as e:
        memories = ""
        status = f"Memory retrieval error: {str(e)}"
        
    return {
        "processed_data": memories,
        "status": status
    }

def execute_node(state: AgentState) -> AgentState:
    """Execute python code generated by the agent."""
    code = state.get("code", "")
    
    if not code:
        return {
            "execution_result": "No code provided to execute.",
            "status": "Skipped execution"
        }
        
    try:
        result = code_tool.invoke({"code": code})
        status = "Code executed successfully."
    except Exception as e:
        result = str(e)
        status = f"Code execution error: {str(e)}"
        
    return {
        "execution_result": str(result),
        "status": status
    }

def file_management_node(state: AgentState) -> AgentState:
    """Save the execution result to an output file."""
    execution_result = state.get("execution_result", "")
    
    try:
        # Saving output into a default execution log file
        output_tool.invoke({"file_path": "executor_output.txt", "text": execution_result})
        status = "Execution result saved to file."
    except Exception as e:
        status = f"File saving error: {str(e)}"
        
    return {
        "status": status
    }

def store_node(state: AgentState) -> AgentState:
    """Store the execution result into Chroma DB for future reference."""
    execution_result = state.get("execution_result", "")
    
    if not execution_result:
        return {"status": "No execution result to store."}
        
    try:
        store_memory_tool.invoke({"text": f"Code Execution Result: {execution_result}"})
        status = "Execution result stored in Chroma DB."
    except Exception as e:
        status = f"Memory storing error: {str(e)}"
        
    return {
        "status": status
    }

def build_graph():
    graph = StateGraph(AgentState)
    
    graph.add_node("retrieve", retrieve_node)
    graph.add_node("execute", execute_node)
    graph.add_node("file_management", file_management_node)
    graph.add_node("store", store_node)
    
    graph.add_edge(START, "retrieve")
    graph.add_edge("retrieve", "execute")
    graph.add_edge("execute", "file_management")
    graph.add_edge("file_management", "store")
    graph.add_edge("store", END)
    
    return graph.compile()
